package com.tnz.business.std;

/**
 * All the business exception generated by the software should extend this base class
 * @author Terenzio
 *
 */
public abstract class BusinessException extends RuntimeException {

	/**
	 * Helper method to check the specific exception code
	 * @param code the code to be checked
	 * @return true if there is a match
	 */
	protected boolean isCode(String code) {
		return this.getMessage() == code;
	}
	
	protected BusinessException(String code) {
		super(code);
	}
}
